# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'kde/kdegames/libkdegames' : '@latest'
    'frameworks/kconfig': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/kcrash': '@stable'
    'frameworks/kdbusaddons': '@stable'
    'frameworks/kdoctools': '@stable'
    'frameworks/kguiaddons': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kxmlgui': '@stable'
    'frameworks/kwidgetsaddons': '@stable'
